
create table if not exists public.concerts (
  id uuid primary key default gen_random_uuid(),
  external_id text,
  artist text not null,
  genre text,
  city text,
  state text,
  venue text,
  starts_at timestamptz not null,
  price_from numeric,
  currency text not null default 'INR',
  source text not null,
  source_url text not null,
  status text not null default 'upcoming',
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source, external_id)
);

create index if not exists concerts_starts_at_idx on public.concerts(starts_at);
create index if not exists concerts_city_idx on public.concerts(city);
create index if not exists concerts_state_idx on public.concerts(state);

alter table public.concerts enable row level security;

drop policy if exists "Public can read upcoming concerts" on public.concerts;
create policy "Public can read upcoming concerts"
on public.concerts for select
to anon, authenticated
using (status = 'upcoming' and starts_at >= now());

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null,
  source_count integer default 0,
  event_count integer default 0,
  error text
);

-- 00:00 IST = 18:30 UTC on the previous day.
-- Supabase Cron schedules in the database timezone, normally UTC.
-- If your project timezone differs, adjust this expression/schedule.
select cron.schedule(
  'concertz-nightly-sync',
  '30 18 * * *',
  $$select net.http_post(
    url := current_setting('app.settings.sync_function_url', true),
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.sync_secret', true)
    ),
    body := '{}'::jsonb
  )$$
)
where not exists (
  select 1 from cron.job where jobname = 'concertz-nightly-sync'
);
